version: '2'
services:
  sonarqube:
    container_name: sonarqube
    image: 10.136.44.42:5000/sonarqube:9.2-community
    ports:
      - "9001:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    depends_on:
      - init
  sonarqubedb:
    container_name: sonarqubedb
    image: 10.136.44.42:5000/postgres:14
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_postgresql:/var/lib/postgresql
      - sonarqube_postgresql_data:/var/lib/postgresql/data
  init:
    container_name: init
    image: bash
    privileged: true
    user: root
    volumes:
      - ./sonar/init.sh:/mnt/init.sh
    command: ["sh", "-e", "/mnt/init.sh"]

networks:
  default:
    name: amco-net
    external: true

volumes:
  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  sonarqube_logs:
    name: sonarqube_logs
  sonarqube_bundled-plugins:
    name: sonarqube_bundled-plugins
  sonarqube_postgresql:
    name: sonarqube_postgresql
  sonarqube_postgresql_data:
    name: sonarqube_postgresql_data
